import "./globals.css"
import { Inter } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@/components/analytics"
// import { ModeToggle } from "@/components/mode-toggle"
import { Header } from "@/components/layout/header"
import { Footer } from "@/components/layout/footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export type tabDetail = { href: string; name: string }

const tabList: tabDetail[] = [
  { href: "/", name: "Home" },
  { href: "/about", name: "Tentang Kami" },
  { href: "/service", name: "Pelayanan" },
  { href: "/experience", name: "Pengalaman" },
  { href: "/gallery", name: "Galeri" },
  { href: "/contact", name: "Kontak" },
]

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`bg-white text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-50 ${inter.className}`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <header>
            <Header tabs={tabList} />
          </header>
          <main>{children}</main>
          {/* <div className="mx-auto max-w-2xl px-4 py-10">
          </div> */}
          <Analytics />
        </ThemeProvider>
      </body>
      <Footer />
    </html>
  )
}
